<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/18 07:58:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dice',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
