<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/20 09:25:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dice',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
